# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.byrtanimation.root] run return 0
execute on passengers if entity @s[tag=aj.byrtanimation.data] unless data entity @s {data:{rigHash: '03daa09e5b13edcd9a742dabaa9aeb33eb5d7cb7cc3fedbe1b09cfd6e4a965b3'}} on vehicle run function animated_java:byrtanimation/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1