# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.byrtanimation.root] run return 0
execute on passengers if entity @s[tag=aj.byrtanimation.data] unless data entity @s {data:{rigHash: 'd9bde670a6725f119e757fb1554532e707b095bb748fa6d0e31dbe9184737922'}} on vehicle run function animated_java:byrtanimation/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1